### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by theamircodex** [sentrionic/Valkyrie#10]
Hello! sorry for bothering you 🙏🙏

I'm beginner and want to learn more about React and TS and I don't wanna just copy and paste something
and my request is please send me a concept map of Valkyrie App , Please . it will help me to understand more about this project 
Thanks for this amazing project 
Please send it to me 🙏
something like these concept maps
 
![Consept](https://user-images.githubusercontent.com/92599653/141650102-a3925491-9920-44a5-8bf7-f29e918016b8.png)
![image](https://user-images.githubusercontent.com/92599653/141650172-939a4253-3134-429c-8038-b6110cd14253.png)
:

**Comment by sentrionic** [comment]
Sorry but I currently do not have time to create something like that. I also wouldn't really know how to do that for a website.

If you want to learn more about React I would either recommend the [official docs](https://beta.reactjs.org/) or [Ben Awad's](https://www.youtube.com/c/BenAwad97/videos) tutorials. This app is based on his Slack tutorial series.

**Comment by theamircodex** [comment]
Okay Thanks u <3
