### ISSUE TITLE
Server Down.

### ISSUE THREAD

**Issue by Adithr123** [sentrionic/Valkyrie#12]

**Comment by Adithr123** [comment]
nvm, its back up

**Comment by Adithr123** [comment]
Nop, there back down

**Comment by Adithr123** [comment]
![image](https://user-images.githubusercontent.com/85714072/146483591-38d90893-7be6-4c6b-89e7-e34f0b49bfc5.png)

**Comment by sentrionic** [comment]
I restarted the server. Thanks for informing me.
