### ISSUE TITLE
Netify launching doesnt work.

### ISSUE THREAD

**Issue by Adithr123** [sentrionic/Valkyrie#13]
![image](https://user-images.githubusercontent.com/85714072/146482759-7f0e3d8d-ec26-4b4d-954b-06a2a93895cb.png)

**Comment by sentrionic** [comment]
The icon is just to indicate that the actual website (the frontend) was deployed successfully. 

Only members of the team (which means only me) is actually allowed to see the management board.

I guess this was related to #12.
