### ISSUE TITLE
Can we use firebase for social auth?

### ISSUE THREAD

**Issue by riveraj33** [sentrionic/Valkyrie#16]
Thanks for this awesome project. Regarding login. Can we use firebase authentication for this script? I'm super new to this, so if someone could point me in the right direction, I'd appreciate it! TYIA

**Comment by sentrionic** [comment]
It is possible to use Firebase for authentication, as seen [in this article](https://medium.com/wesionary-team/authenticate-rest-api-in-go-with-firebase-authentication-36cdf7c254c). But as you can see you would have to replace the session authentication with token authentication, which requires a little rewriting.
