### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by BlackReaper33** [sentrionic/Valkyrie#18]
I app works fine on local host but when i convert my localhost to a public URL using ngrok or localtunnel it gives me the following CORS error 
`Access to XMLHttpRequest at 'http://localhost:4000/api/account/register' from origin 'https://animeea.loca.lt' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by sentrionic** [comment]
Did you set the `domain` variable in the environment, since it still says localhost in the error?

**Comment by BlackReaper33** [comment]
> Did you set the `domain` variable in the environment, since it still says localhost in the error?

Oh crap i didn't wait lemme do it  real quick. And thank you for reaching out to me♡

**Comment by BlackReaper33** [comment]
> Did you set the `domain` variable in the environment, since it still says localhost in the error?

Same error:
`Access to XMLHttpRequest at 'http://localhost:4000/api/account/register' from origin 'http://animeea.loca.lt' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

My **.env** file:
`PORT=4000
DATABASE_URL=postgresql://postgres:xxxxx@localhost:5432/valkyrie
REDIS_URL=redis://localhost:6379
CORS_ORIGIN=http://localhost:3000
SECRET=thisissecret
DOMAIN=https://animeea.loca.lt
AWS_ACCESS_KEY=key
AWS_SECRET_ACCESS_KEY=otherkey
AWS_STORAGE_BUCKET_NAME=bucket
AWS_S3_REGION=region
GMAIL_USER=example@gmail.com
GMAIL_PASSWORD=password
HANDLER_TIMEOUT=5
MAX_BODY_BYTES=4194304 # 4MB in Bytes = 4 * 1024 * 1024`

**Comment by BlackReaper33** [comment]
Same error:Access to XMLHttpRequest at 'http://localhost:4000/api/account/register' from origin 'http://animeea.loca.lt' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested ***@***.***:5432/valkyrie REDIS_URL=redis://localhost:6379 CORS_ORIGIN=http://localhost:3000 SECRET=thisissecret DOMAIN=https://animeea.loca.lt AWS_ACCESS_KEY=key AWS_SECRET_ACCESS_KEY=otherkey AWS_STORAGE_BUCKET_NAME=bucket AWS_S3_REGION=region ***@***.*** GMAIL_PASSWORD=password HANDLER_TIMEOUT=5 MAX_BODY_BYTES=4194304 # 4MB in Bytes = 4 * 1024 * 1024 Sent from Mail for Windows From: sentrionicSent: Tuesday, June 7, 2022 7:17 PMTo: sentrionic/ValkyrieCc: Black Reaper; AuthorSubject: Re: [sentrionic/Valkyrie] CORS Error (Issue #18) Did you set the domain variable in the environment, since it still says localhost in the error?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com

**Comment by sentrionic** [comment]
You also need to change the `CORS_ORIGIN` variable.

Mine is set to `https://valkyrieapp.xyz` for example, while the domain is set to `.valkyrieapp.xyz`.

**Comment by BlackReaper33** [comment]
> You also need to change the `CORS_ORIGIN` variable.
> 
> Mine is set to `https://valkyrieapp.xyz` for example, while the domain is set to `.valkyrieapp.xyz`.

Same error..... please help...
**.env file:**
PORT=4000
DATABASE_URL=postgresql://postgres:billu420@localhost:5432/valkyrie
REDIS_URL=redis://localhost:6379
CORS_ORIGIN=https://animeea.loca.lt
SECRET=thisissecret
DOMAIN=.animeea.loca.lt
AWS_ACCESS_KEY=key
AWS_SECRET_ACCESS_KEY=otherkey
AWS_STORAGE_BUCKET_NAME=bucket
AWS_S3_REGION=region
GMAIL_USER=example@gmail.com
GMAIL_PASSWORD=password
HANDLER_TIMEOUT=5
MAX_BODY_BYTES=4194304 # 4MB in Bytes = 4 * 1024 * 1024

**Comment by sentrionic** [comment]
I'm not familiar with localtunnel so I don't know if it needs extra setup.
I checked my environment variables and the only addition I have is that I set `GIN_MODE` to `release`.

Where is your web client hosted?

**Comment by BlackReaper33** [comment]
> I'm not familiar with localtunnel so I don't know if it needs extra setup. I checked my environment variables and the only addition I have is that I set `GIN_MODE` to `release`.
> 
> Where is your web client hosted?

My client is currently host on my pc atm i convert my localhost:3000 to a public url using localtunnel "https://animeea.loca.lt"
And my server is host on my pc as well at localhost:4000

**Comment by BlackReaper33** [comment]
> I think your server needs to run with the same domain, like `https://api.animeea.loca.lt`. I would recommend searching something like "localtunnel cors" and following some of the results.

Which service are you using to host your domains? And is there any other way to contact you? I checked your twitter account but unfortunately its private

**Comment by sentrionic** [comment]
I use Heroku to host the server and Netlify to host the website. You would need to use the paid tier to fully host the project since Heroku's free tier doesn't allow custom domains. 

Github is the best way to contact me.

**Comment by BlackReaper33** [comment]
> I use Heroku to host the server and Netlify to host the website. You would need to use the paid tier to fully host the project since Heroku's free tier doesn't allow custom domains.
> 
> Github is the best way to contact me.

And how would i host my postgres and redis on heroku free version?

**Comment by sentrionic** [comment]
Heroku offers add-on you can easily attach to your app.

**Comment by BlackReaper33** [comment]
> Heroku offers add-on you can easily attach to your app.

When i load my application on heroku it says **"Error loading .env file"** and when i goto my site it gives the following error in the logs:
`2022-06-07T18:12:22.999193+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=animeempire5.herokuapp.com request_id=9700d7b6-ba87-49e3-aaa9-da6e65926e25 fwd="182.185.41.22" dyno= connect= service= status=503 bytes= protocol=https2022-06-07T18:12:23.408210+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=animeempire5.herokuapp.com request_id=c52837e2-8bda-49eb-aaf0-86ed618a8efa fwd="182.185.41.22" dyno= connect= service= status=503 bytes= protocol=https`

**".env file":**
PORT=4000
DATABASE_URL=postgresql://postgres:xxxxx@localhost:5432/valkyrie
REDIS_URL=redis://localhost:6379
CORS_ORIGIN=https://animeempire5.herokuapp.com/
SECRET=thisissecret
DOMAIN=.animeempire5.herokuapp.com/
AWS_ACCESS_KEY=key
AWS_SECRET_ACCESS_KEY=otherkey
AWS_STORAGE_BUCKET_NAME=bucket
AWS_S3_REGION=region
GMAIL_USER=example@gmail.com
GMAIL_PASSWORD=password
HANDLER_TIMEOUT=5
MAX_BODY_BYTES=4194304 # 4MB in Bytes = 4 * 1024 * 1024

I have added heroku postgres  but couldn't add redis since i need to add credit card details- ;-;
Can please recommend any other site or solution. I really wish to use you repository....

**Comment by BlackReaper33** [comment]
> Sadly there isn't really a good way to host stuff for free. By the way, you need to set the variables in the settings tab and the config vars fields. But as I said you won't be able to run the project without one of the paid tiers on Heroku.

Does the flutter version have the same issue-?

**Comment by sentrionic** [comment]
If you mean cors issues then you, since cors is related to browsers.

**Comment by BlackReaper33** [comment]
> If you mean cors issues then you, since cors is related to browsers.

Well thanks for guidance!! Ill open up issue if i have further questions  :D

**Comment by BlackReaper33** [comment]
Explained Issue

**Comment by BlackReaper33** [comment]
so im deployed my web on the netlify and added my website like to my heroku config vars in front of cors_origin however its still showing blocked by cors policy.
help please

**Comment by sentrionic** [comment]
What values did you set for you environment variables? If it worked locally, but not in production, then the issue should be in those.

**Comment by BlackReaper33** [comment]
Do i have to add environmental variables in the netlify as well?

**Comment by sentrionic** [comment]
On Netlify I have `REACT_APP_API_URL` set to `https://api.valkyrieapp.xyz/api` and `REACT_APP_API_WS` to `https://api.valkyrieapp.xyz/ws`, but I'm sure those are already set for you since you get a response from your server.

**Comment by BlackReaper33** [comment]
You added them as env right? Because i haven't added any env values in my netlify app

**Comment by BlackReaper33** [comment]
my .env.development file is
`browser=none
REACT_APP_API=https://animeempire.herokuapp.com
REACT_APP_WS=ws://animeempire.herokuapp.com//ws`

and .env.production is
`REACT_APP_API=https://api.valkyrieapp.xyz
REACT_APP_WS=wss://api.valkyrieapp.xyz/ws
browser=none
`

help

**Comment by sentrionic** [comment]
The `.env.production` is used during the build process, so you need to add the values from your `.env.development` file. The `.env.development` is used when you locally run the client.

**Comment by BlackReaper33** [comment]
resolved

**Comment by BlackReaper33** [comment]
Hey sentrionic! Can you please guide on how to upload web on heroku as well? 
I uploaded it to heroku but its again giving cors error. I even added the web url to CORS_ORIGIN on the server end but its not working...
I also added the server url to the web react place as well

**Comment by sentrionic** [comment]
Do they both run on the same app or different ones?

**Comment by BlackReaper33** [comment]
Trying to run both on heroku

**Comment by sentrionic** [comment]
Did you deploy them on two different Heroku apps?

**Comment by BlackReaper33** [comment]
I did with 2 different accounts

**Comment by BlackReaper33** [comment]
But you said domains have to be same to avoid 401 unauthorised error

**Comment by sentrionic** [comment]
Yeah, and you said you deployed with two different accounts, meaning you will have two different domains since heroku requires them to be unique.

**Comment by BlackReaper33** [comment]
My server is: myapp.herokuapp.com
My web is: myappweb.herokuapp.com

The domains are same

**Comment by sentrionic** [comment]
Well, I don't have much experience hosting both on Heroku. What you could look into is [statically serving the frontend from the server](https://medium.com/@synapticsynergy/serving-a-react-app-with-golang-using-gin-c6402ee64a4b).

**Comment by BlackReaper33** [comment]
Ok so i got the cors error to go away, but despite being the domain same of both the ends its still giving 401 unauthorised error

**Comment by BlackReaper33** [comment]
In the env production do i need to change browser from none to chrome or anything else?

**Comment by sentrionic** [comment]
The `browser` variable just tells CRA not to automatically open a browser window during start, which is something I don't like during development.

As for your other error, it's not really possible for me to debug. You could try [this video](https://www.youtube.com/watch?v=nfNrfi7HmLs).

**Comment by BlackReaper33** [comment]
Are credentials set to true on web end? Because im unable to find the the file

**Comment by sentrionic** [comment]
It's defined in `setupAxios.ts `.

**Comment by BlackReaper33** [comment]
Will it be possible if i add you to my heroku team and maybe you can upload valkyrie, and see what might be the issue-?

**Comment by sentrionic** [comment]
I am not gonna play tech support no.
