### ISSUE TITLE
could not parse MAX_BODY_BYTES 

### ISSUE THREAD

**Issue by BlackReaper33** [sentrionic/Valkyrie#22]
`Failure to inject data sources: could not parse MAX_BODY_BYTES as int: strconv.ParseInt: parsing "": invalid syntax`
so now this error is showing up even though i added and then removed the MAX_BODY_BYTES from config vars, both time it gave me the same error

**Comment by sentrionic** [comment]
1. `MAX_BODY_BYTES` is set to `4194304` in my vars.
2. Github Issues are meant for issues with the code of the repository and are not meant as support tickets.

**Comment by BlackReaper33** [comment]
.
