### ISSUE TITLE
Deploy web at Netlify

### ISSUE THREAD

**Issue by BlackReaper33** [sentrionic/Valkyrie#23]
First off thank you for making such outstanding app really appreciate it!!
Secondly can you please guide me how to deploy web folder on netlify? Like what do i add in environment variables? Do i add the .env.production or .env.developmemt?
Please help and do i change core origin variables to my netlify link in the server end?

**Comment by sentrionic** [comment]
First, for session cookies to work, you need to own a domain name you can use on your backend and Netlify.
For the `.env.production` file you need to change the given name to the domain you own. The `production` one will be automatically used during the build process. 
For `CORS_ORIGIN` you set your domain, e.g. `https://valkyrieapp.xyz`, for `DOMAIN` I have `.valkyrieapp.xyz`.
As for how you deploy to Netlify, you best google some tutorials, but the general gist is to download their CLI, build the web with `yarn build`, change into the `build` directory and the upload the site using the Netlify CLI.

**Comment by BlackReaper33** [comment]
In `.env.production` and `DOMAIN` I need to add my server domain link right? And in `CORS_ORIGIN` my web domain link?

**Comment by sentrionic** [comment]
In ``.env.prod` you set the server domain yes. `CORS_ORIGIN` uses the web domain, `DOMAIN` uses a version like `.your-domain.com` (notice the lack of https or other prefixes).

**Comment by BlackReaper33** [comment]
Solved
