### ISSUE TITLE
Invalid session (friend request)

### ISSUE THREAD

**Issue by BlackReaper33** [sentrionic/Valkyrie#25]
Hey sentrionic! So um i was testing out the friend request module and whenever I tried added a friend it said invalid session.  I tried with different accounts but it still said the same...
Any reason why its saying it :')

**Comment by sentrionic** [comment]
Invalid Session means that no `userID` was found in the session. As for why it's not set I can't tell you, you will have to check your logs.

**Comment by BlackReaper33** [comment]
but the account does exist- how is it not found?

**Comment by sentrionic** [comment]
The auth middleware in `auth_user.go` checks if a id is stored in the current session and returns the invalid error if that's not the case. So for some reason either the id was not set or the session expired.

**Comment by BlackReaper33** [comment]
And before i close this issue one last question 
`flutter create --org package_name .`
I would add valkyrie_app instead of package_name right?

**Comment by sentrionic** [comment]
As the CLI says: `The organization responsible for your new Flutter project, in reverse domain name notation.`, which would be `xyz.valkyrieapp` in my case.

**Comment by BlackReaper33** [comment]
when im trying to create server via website it gives e the following error in the console:
`POST https://myapp.herokuapp.com/api/guilds/create 401 (Unauthorized)`

**Comment by sentrionic** [comment]
I'm sorry but I really can't help you

**Comment by BlackReaper33** [comment]
Where do you think the error lies?

**Comment by sentrionic** [comment]
There's something wrong with your session setup. Are you sure the cookie gets set?

**Comment by BlackReaper33** [comment]
how do i set that-?

**Comment by sentrionic** [comment]
It should be automatically set by the backend.

You can check by opening the Chrome dev tools and then going to Application > Cookies > Website Name.

![image](https://user-images.githubusercontent.com/38354571/181183861-d1e82b86-9f6c-4b05-b625-d6a1b34ab74a.png)

**Comment by BlackReaper33** [comment]
nothing is loaded into my cookies

**Comment by sentrionic** [comment]
Are your backend and frontend running with the same domain name?

**Comment by BlackReaper33** [comment]
no my backend is https://myapp.herokuapp.com/
and my fronted is https://myapp.netlify.app/

**Comment by sentrionic** [comment]
I've told you at the very beginning of your many questions that they need to run with the same domain name for sessions to work.

**Comment by BlackReaper33** [comment]
is there a way around-? i did add my frontend to my env

**Comment by sentrionic** [comment]
The only way around is to replace sessions with something like JWT.
