### ISSUE TITLE
Allowing multiple domains?

### ISSUE THREAD

**Issue by BlackReaper33** [sentrionic/Valkyrie#27]
Hey can you tell if its possible to add multiple domains in env file so it accepts data from different domains?

**Comment by sentrionic** [comment]
Which env file? The server and the client have one so you need to be more specific.

**Comment by BlackReaper33** [comment]
Server env file

**Comment by sentrionic** [comment]
With domain do you mean the server's domain name or different web domains?

**Comment by BlackReaper33** [comment]
Different web domain in the server folder .env file.
Hope if i add a second Different domain the server will accept it and they'll share cookies

**Comment by sentrionic** [comment]
You could add different domain with variables like `CORS_ORIGIN_1` etc. and then adding them to the `cors` allowed origins list.

**Comment by BlackReaper33** [comment]
And what about adding second domain?

**Comment by sentrionic** [comment]
Based on the source code of the session library, it only seems to allow one domain.

**Comment by BlackReaper33** [comment]
Can you add option of second domain on next update or allow different domains to communicate

**Comment by sentrionic** [comment]
Like I said, the library I use for managing sessions only allows for one domain.

**Comment by BlackReaper33** [comment]
Maybe jwt as you mentioned earlier- since making both domains same is pretty hard- ^^;

**Comment by sentrionic** [comment]
I won't rewrite my authentication system. Sessions are more secure than JWT and easier to manage.

You are putting a lot of effort into getting this thing running. You do know there are other chat applications on GitHub that also have a lot more features and are build by a team.

**Comment by BlackReaper33** [comment]
Well this is easier to understand and i like how closely it resembles discord

**Comment by sentrionic** [comment]
The [tutorial](https://github.com/JacobSNGoodwin/memrizr) this server is based on uses JWT, you could take a look and see how he implements them.
