### ISSUE TITLE
issue in starting server

### ISSUE THREAD

**Issue by AmirShooter** [sentrionic/Valkyrie#5]
hello excuse me i have a error and i need help :((
![image](https://user-images.githubusercontent.com/77153410/129084572-49deda62-2045-4639-9057-83b501843bcb.png)

**Comment by AmirShooter** [comment]
help plz

**Comment by AmirShooter** [comment]
no i haven't . this is my database.ts src 

![image](https://user-images.githubusercontent.com/77153410/129281824-a0f763ac-a690-4473-8876-08af8f8e6168.png)

**Comment by AmirShooter** [comment]
sorry how can i run server in heroku ??
i don't about it :((

**Comment by sentrionic** [comment]
Before you host it on Heroku you should try to get it working on your local machine.

You can check https://github.com/sentrionic/Valkyrie/issues/1 where I helped someone host the backend on Heroku.

**Comment by AmirShooter** [comment]
Oh okay thank you a lot 😍💖
