### ISSUE TITLE
Login API responds with 401 Error

### ISSUE THREAD

**Issue by xtc-dev** [sentrionic/Valkyrie#6]
I tried logging in just a few moments ago, and I was greeted with a "invalid credentials" error. I was sure I put in the correct information, as I've had it saved, but I checked the console to see a "POST https://api.valkyrieapp.xyz/api/account/login 401 (Unauthorized))" message. What can I do to fix this?

**Comment by sentrionic** [comment]
Just today I wiped the databases records since Heroku's free Postgres has a limit of 10k rows.
So you would have to create a new account.

**Comment by xtc-dev** [comment]
Oh that makes a ton of sense! Thanks for the reply, I really enjoy this project! :)

**Comment by sentrionic** [comment]
You are right. Apparently I had to restart after wiping the DB.
It should work now.

**Comment by xtc-dev** [comment]
Thanks a lot!
